//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Autoscaling) DeepCopyInto(out *Autoscaling) {
	*out = *in
	if in.MinScale != nil {
		in, out := &in.MinScale, &out.MinScale
		*out = new(int32)
		**out = **in
	}
	if in.MaxScale != nil {
		in, out := &in.MaxScale, &out.MaxScale
		*out = new(int32)
		**out = **in
	}
	if in.TargetConcurrency != nil {
		in, out := &in.TargetConcurrency, &out.TargetConcurrency
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Autoscaling.
func (in *Autoscaling) DeepCopy() *Autoscaling {
	if in == nil {
		return nil
	}
	out := new(Autoscaling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Eventing) DeepCopyInto(out *Eventing) {
	*out = *in
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = make([]EventingFilter, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Eventing.
func (in *Eventing) DeepCopy() *Eventing {
	if in == nil {
		return nil
	}
	out := new(Eventing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventingFilter) DeepCopyInto(out *EventingFilter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventingFilter.
func (in *EventingFilter) DeepCopy() *EventingFilter {
	if in == nil {
		return nil
	}
	out := new(EventingFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioTraffic) DeepCopyInto(out *IstioTraffic) {
	*out = *in
	if in.VirtualServiceRefs != nil {
		in, out := &in.VirtualServiceRefs, &out.VirtualServiceRefs
		*out = make([]NamespacedObjectRef, len(*in))
		copy(*out, *in)
	}
	if in.DestinationRuleRefs != nil {
		in, out := &in.DestinationRuleRefs, &out.DestinationRuleRefs
		*out = make([]NamespacedObjectRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioTraffic.
func (in *IstioTraffic) DeepCopy() *IstioTraffic {
	if in == nil {
		return nil
	}
	out := new(IstioTraffic)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnativeAdoption) DeepCopyInto(out *KnativeAdoption) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnativeAdoption.
func (in *KnativeAdoption) DeepCopy() *KnativeAdoption {
	if in == nil {
		return nil
	}
	out := new(KnativeAdoption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KnativeAdoption) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnativeAdoptionList) DeepCopyInto(out *KnativeAdoptionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KnativeAdoption, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnativeAdoptionList.
func (in *KnativeAdoptionList) DeepCopy() *KnativeAdoptionList {
	if in == nil {
		return nil
	}
	out := new(KnativeAdoptionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KnativeAdoptionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnativeAdoptionSpec) DeepCopyInto(out *KnativeAdoptionSpec) {
	*out = *in
	out.SourceRef = in.SourceRef
	in.Autoscaling.DeepCopyInto(&out.Autoscaling)
	in.ScaleDownProbe.DeepCopyInto(&out.ScaleDownProbe)
	if in.Eventing != nil {
		in, out := &in.Eventing, &out.Eventing
		*out = new(Eventing)
		(*in).DeepCopyInto(*out)
	}
	if in.Traffic != nil {
		in, out := &in.Traffic, &out.Traffic
		*out = new(Traffic)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnativeAdoptionSpec.
func (in *KnativeAdoptionSpec) DeepCopy() *KnativeAdoptionSpec {
	if in == nil {
		return nil
	}
	out := new(KnativeAdoptionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnativeAdoptionStatus) DeepCopyInto(out *KnativeAdoptionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SourceSnapshot != nil {
		in, out := &in.SourceSnapshot, &out.SourceSnapshot
		*out = new(SourceSnapshot)
		(*in).DeepCopyInto(*out)
	}
	if in.LastScaleDownProbe != nil {
		in, out := &in.LastScaleDownProbe, &out.LastScaleDownProbe
		*out = new(ProbeStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Traffic != nil {
		in, out := &in.Traffic, &out.Traffic
		*out = new(TrafficStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.OwnedTriggers != nil {
		in, out := &in.OwnedTriggers, &out.OwnedTriggers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnativeAdoptionStatus.
func (in *KnativeAdoptionStatus) DeepCopy() *KnativeAdoptionStatus {
	if in == nil {
		return nil
	}
	out := new(KnativeAdoptionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedObjectRef) DeepCopyInto(out *NamespacedObjectRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedObjectRef.
func (in *NamespacedObjectRef) DeepCopy() *NamespacedObjectRef {
	if in == nil {
		return nil
	}
	out := new(NamespacedObjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedRoute) DeepCopyInto(out *ObservedRoute) {
	*out = *in
	if in.Ready != nil {
		in, out := &in.Ready, &out.Ready
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedRoute.
func (in *ObservedRoute) DeepCopy() *ObservedRoute {
	if in == nil {
		return nil
	}
	out := new(ObservedRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbeStatus) DeepCopyInto(out *ProbeStatus) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbeStatus.
func (in *ProbeStatus) DeepCopy() *ProbeStatus {
	if in == nil {
		return nil
	}
	out := new(ProbeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleDownProbe) DeepCopyInto(out *ScaleDownProbe) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleDownProbe.
func (in *ScaleDownProbe) DeepCopy() *ScaleDownProbe {
	if in == nil {
		return nil
	}
	out := new(ScaleDownProbe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceRef) DeepCopyInto(out *SourceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceRef.
func (in *SourceRef) DeepCopy() *SourceRef {
	if in == nil {
		return nil
	}
	out := new(SourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceSnapshot) DeepCopyInto(out *SourceSnapshot) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(v1.ServiceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Traffic != nil {
		in, out := &in.Traffic, &out.Traffic
		*out = new(TrafficSnapshot)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceSnapshot.
func (in *SourceSnapshot) DeepCopy() *SourceSnapshot {
	if in == nil {
		return nil
	}
	out := new(SourceSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Traffic) DeepCopyInto(out *Traffic) {
	*out = *in
	if in.Istio != nil {
		in, out := &in.Istio, &out.Istio
		*out = new(IstioTraffic)
		(*in).DeepCopyInto(*out)
	}
	if in.ServicePort != nil {
		in, out := &in.ServicePort, &out.ServicePort
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Traffic.
func (in *Traffic) DeepCopy() *Traffic {
	if in == nil {
		return nil
	}
	out := new(Traffic)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficObjectSnapshot) DeepCopyInto(out *TrafficObjectSnapshot) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficObjectSnapshot.
func (in *TrafficObjectSnapshot) DeepCopy() *TrafficObjectSnapshot {
	if in == nil {
		return nil
	}
	out := new(TrafficObjectSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficSnapshot) DeepCopyInto(out *TrafficSnapshot) {
	*out = *in
	if in.VirtualServices != nil {
		in, out := &in.VirtualServices, &out.VirtualServices
		*out = make([]TrafficObjectSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DestinationRules != nil {
		in, out := &in.DestinationRules, &out.DestinationRules
		*out = make([]TrafficObjectSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficSnapshot.
func (in *TrafficSnapshot) DeepCopy() *TrafficSnapshot {
	if in == nil {
		return nil
	}
	out := new(TrafficSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficStatus) DeepCopyInto(out *TrafficStatus) {
	*out = *in
	if in.ObservedRoutes != nil {
		in, out := &in.ObservedRoutes, &out.ObservedRoutes
		*out = make([]ObservedRoute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficStatus.
func (in *TrafficStatus) DeepCopy() *TrafficStatus {
	if in == nil {
		return nil
	}
	out := new(TrafficStatus)
	in.DeepCopyInto(out)
	return out
}
